"""Initial migration

Revision ID: 037f5e7f2ab3
Revises: 
Create Date: 2025-03-12 16:10:07.255796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037f5e7f2ab3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ms_cctv',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_lokasi', sa.String(length=255), nullable=False),
    sa.Column('nama_cctv', sa.String(length=255), nullable=False),
    sa.Column('stream_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('nama_pengelola', sa.String(length=255), nullable=True),
    sa.Column('protocol', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('tag_kategori', sa.String(length=50), nullable=False),
    sa.Column('matra', sa.String(length=50), nullable=False),
    sa.Column('nama_kabupaten_kota', sa.String(length=255), nullable=True),
    sa.Column('nama_provinsi', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ms_roi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_cctv', sa.UUID(), nullable=False),
    sa.Column('nama_cctv', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('roi', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_cctv'], ['ms_cctv.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avg_vhc_dwelling_time_per_roi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_cctv', sa.UUID(), nullable=False),
    sa.Column('nama_cctv', sa.String(length=255), nullable=False),
    sa.Column('id_roi', sa.UUID(), nullable=False),
    sa.Column('roi_label', sa.String(length=100), nullable=False),
    sa.Column('tipe_vhc', sa.String(length=50), nullable=False),
    sa.Column('waktu_tunggu_rata_rata', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cctv'], ['ms_cctv.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_roi'], ['ms_roi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counted_vhc_per_roi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cctv_name', sa.String(length=255), nullable=False),
    sa.Column('id_cctv', sa.UUID(), nullable=False),
    sa.Column('id_roi', sa.UUID(), nullable=False),
    sa.Column('roi_label', sa.String(length=100), nullable=False),
    sa.Column('tipe_vhc', sa.String(length=50), nullable=False),
    sa.Column('jml_vhc', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cctv'], ['ms_cctv.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_roi'], ['ms_roi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('est_avg_speed_per_roi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_cctv', sa.UUID(), nullable=False),
    sa.Column('nama_cctv', sa.String(length=255), nullable=False),
    sa.Column('id_roi', sa.UUID(), nullable=False),
    sa.Column('roi_label', sa.String(length=100), nullable=False),
    sa.Column('tipe_vhc', sa.String(length=50), nullable=False),
    sa.Column('rata_rata_kecepatan', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cctv'], ['ms_cctv.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_roi'], ['ms_roi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('est_avg_speed_per_roi')
    op.drop_table('counted_vhc_per_roi')
    op.drop_table('avg_vhc_dwelling_time_per_roi')
    op.drop_table('ms_roi')
    op.drop_table('ms_cctv')
    # ### end Alembic commands ###
