"""Initial migration

Revision ID: 7b403d51053b
Revises: 
Create Date: 2025-02-10 16:40:08.629580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b403d51053b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ms_CCTV',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('CCTV_Name', sa.String(length=255), nullable=False),
    sa.Column('Ruas_Name', sa.String(length=255), nullable=True),
    sa.Column('Stream_url', sa.Text(), nullable=False),
    sa.Column('Lat', sa.Float(), nullable=True),
    sa.Column('Long', sa.Float(), nullable=True),
    sa.Column('BUJT', sa.String(length=100), nullable=True),
    sa.Column('BUJT_NAME', sa.String(length=255), nullable=True),
    sa.Column('Created_at', sa.DateTime(), nullable=True),
    sa.Column('Updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Ms_ROI',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('Id_CCTV', sa.UUID(), nullable=False),
    sa.Column('CCTV_Name', sa.String(length=255), nullable=False),
    sa.Column('Label', sa.String(length=100), nullable=False),
    sa.Column('ROI', sa.JSON(), nullable=False),
    sa.Column('Created_at', sa.DateTime(), nullable=True),
    sa.Column('Updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Id_CCTV'], ['Ms_CCTV.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Avg_VHC_Dwelling_Time_Per_ROI',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('Id_CCTV', sa.UUID(), nullable=False),
    sa.Column('CCTV_Name', sa.String(length=255), nullable=False),
    sa.Column('Id_ROI', sa.UUID(), nullable=False),
    sa.Column('ROI_Label', sa.String(length=100), nullable=False),
    sa.Column('Vhc_Type', sa.String(length=50), nullable=False),
    sa.Column('Vhc_Dwelling_time', sa.Float(), nullable=False),
    sa.Column('Created_at', sa.DateTime(), nullable=True),
    sa.Column('Updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Id_CCTV'], ['Ms_CCTV.Id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Id_ROI'], ['Ms_ROI.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Counted_Vhc_Per_ROI',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('CCTV_Name', sa.String(length=255), nullable=False),
    sa.Column('Id_CCTV', sa.UUID(), nullable=False),
    sa.Column('Id_ROI', sa.UUID(), nullable=False),
    sa.Column('ROI_Label', sa.String(length=100), nullable=False),
    sa.Column('VHC_Type', sa.String(length=50), nullable=False),
    sa.Column('Num_of_VHC', sa.Integer(), nullable=True),
    sa.Column('Created_at', sa.DateTime(), nullable=True),
    sa.Column('Updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Id_CCTV'], ['Ms_CCTV.Id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Id_ROI'], ['Ms_ROI.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Est_Avg_Speed_Per_ROI',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('Id_CCTV', sa.UUID(), nullable=False),
    sa.Column('CCTV_Name', sa.String(length=255), nullable=False),
    sa.Column('Id_ROI', sa.UUID(), nullable=False),
    sa.Column('ROI_Label', sa.String(length=100), nullable=False),
    sa.Column('Vhc_Type', sa.String(length=50), nullable=False),
    sa.Column('Vhc_Avg_Speed_Est', sa.Float(), nullable=False),
    sa.Column('Created_at', sa.DateTime(), nullable=True),
    sa.Column('Updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Id_CCTV'], ['Ms_CCTV.Id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Id_ROI'], ['Ms_ROI.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Est_Avg_Speed_Per_ROI')
    op.drop_table('Counted_Vhc_Per_ROI')
    op.drop_table('Avg_VHC_Dwelling_Time_Per_ROI')
    op.drop_table('Ms_ROI')
    op.drop_table('Ms_CCTV')
    # ### end Alembic commands ###
